karat:
  api:
    timeout: 30 # API call timeout in seconds
    max_concurrency: 10 # max parallel Kafka API calls (e.g. ListConsumerGroupOffsets)
  clusters:
    - name: prod
      mode: read-only
      properties:
        bootstrap.servers: kafka-prod:9094
    - name: dev
      properties:
        bootstrap.servers: kafka-dev:29094
  schema-registries:
    - name: prod
      schema.registry.url: http://schema-registry-prod:8081
    - name: dev
      schema.registry.url: http://schema-registry-dev:8081
  connect:
    - name: prod
      mode: read-only
      url: https://connect-prod:8083
      selected: true
    - name: dev
      url: https://connect-dev:8083
  cli_templates:
    - kcat -b {{bootstrap}} -t {{topic}} -o beginning -f
      '{"Key":"%k","Value":%s,"Timestamp":%T,"Partition":%p,"Offset":%o,"Headers":"%h","Size":%S}\n'
      -u | jq .
    - kcat -b {{bootstrap}} -t {{topic}}
