karat:
  mode: confirm
  api:
    timeout: 30
    max_concurrency: 10
  editor: "vim"
  features:
    topic_size: true
    consumer_group_lag: true
  ui:
    internal_topic_patterns:
      - "^__.*"
      - ".*-changelog$"
      - ".*-repartition$"
